viktomas/godu

README.md
godu.go

Adding flag -l to allow for customizing the file limit.

---

core/command_test.go
core/file_walker.go
core/file_walker_test.go
core/tree_manipulation_test.go
interactive/interactive_test.go
interactive/reporter.go
interactive/reporter_test.go

- reporter can now confidently print / at the end of the dir
- helps with #1

File struct contains information IsDir

---

README.md

Removing redundant installation command

---

godu.go

- and small refactoring of gathering the root argument
part of #14

Informing users that the initial walkthrough might take time

---

README.md
interactive/reporter.go
interactive/reporter_test.go

Padding the File size string for better user experience

---

README.md

README: Add file marking instructions

---

interactive/reporter.go
interactive/reporter_test.go

- this way we won't have weird disalignment
- FYI: @leonklingele

Reserving always space for the marking star.

---

README.md

Adding new README gif with mark func

---

CONTRIBUTING.md

Adding warning to contribution guide

---

core/command_test.go
core/processor_test.go
core/test_utils.go
core/test_utils_test.go
core/tree_helper_test.go
core/tree_manipulation_test.go
interactive/printer_test.go
interactive/reporter_test.go

- creating file trees started to be cumbersome
- now the size computation and parent assignment is taken care of
helps with #29

TstFile and TstFolder for easier testing

---

core/command_test.go
core/processor_test.go
core/test_utils.go
core/test_utils_test.go
core/tree_manipulation_test.go
interactive/printer_test.go
interactive/reporter_test.go

Cheers for the feedback @leonklingele

Refactor test util

---

core/file_walker.go
core/file_walker_test.go
core/test_utils.go
core/test_utils_test.go
interactive/printer_test.go

- moving the FindTestFile method to test utils
@leonklingele: I'm changing code you wrote a bit, could you please have a look and let me know what you think before I merge this?

Recursion in File.Path() method.

---

godu.go
interactive/printer.go
interactive/printer_test.go

@leonklingele: Am I missing something or can the `PrintMarkedFiles` method be simplified like this?

Changing the PrintMakredFiles method

---

core/file_walker.go
core/test_utils.go

Make file walker work concurrently

---

core/file_walker.go

- I think we need to unify tree vs folder vs file naming
- For new person coming to the code it must be confusing as hell
outstanding issues from #36

Polishing getSubTreeConcurrently for now

---

core/file_walker.go
core/file_walker_test.go

- separating concerns
- changing logic a bit (ignored folders are going to be present in the
output but they are always empty)

Simplifying ignoring folders

---

godu.go

Making sure that the app returns correct exit code.

---

state_presenter.go

since https://github.com/gdamore/tcell/pull/140 got merged

Removing tcell hack

---

README.md
parser.go

`hjkl` to move around
`q` to exit
fixes #46

Adding vim like keybindings to godu

---

README.md
godu.go
interactive/printer.go
interactive/printer_test.go

Properly quote file names, add option to print null-terminated lines

---

release.sh

- requires https://github.com/aktau/github-release

Commiting release script coppied from tomnomnom/gron

---

README.md

Updated readme with notes how to run godu from released binary

---

core/file_walker.go
core/file_walker_test.go
go.mod
go.sum
godu.go

fixes #14 
- implementation uses `github.com/gosuri/uilive` library to show users how many folders were walked through

Implemetning folder walking visual update

---

core/command_test.go
core/file_walker_test.go
core/processor_test.go
core/test_utils_test.go
core/tree_manipulation_test.go
go.mod
go.sum
interactive/printer_test.go
interactive/reporter_test.go

Even though this adds a dependency to the project, it will make writing tests in the future easier and the current test easier to understand.

Refactor the test suite to use testify framework

---

interactive/reporter.go
interactive/reporter_test.go
state_presenter.go

fixes #61 
This is initial implementation of a status bar. I'll write tests for the reporter and I'll try to come up with a way how to make the UI of the status bar a bit nicer.

Status bar with total and selected size

---

README.md

Update gif in readme to v1.1

---

core/command.go
core/file_walker.go
core/processor.go
core/test_utils.go
core/tree_manipulation.go
interactive/reporter.go

+ removing exported `ToggleMarkFile` because it was used only in one
place

Updating documentation

---

godu.go
release.sh

Add version info

---

release.sh

And add a comment where can I find the `github-release` binary.

Don't support 386 arch and freebsd

---

README.md

Introduces some trivial improvements to styling and a new **Aliases section**

Add aliases and update documentation style

---

.travis.yml
files/file_walker.go
files/file_walker_test.go
godu.go
ignore.go
ignore_test.go
testCover.sh

I've prepared ground for #19 mainly because I will use the custom ignore function in another project.

Simplifying ignore logic

---

.github/actions/test.yml

Add test GitHub action

---

.github/workflows/release.yml
.github/workflows/test.yml
.gitignore
.goreleaser.yaml

This MR updates the testing task to latest Go version + adds a goreleaser GitHub action

Introduce goreleaser
